# Generated by Django 4.0.2 on 2023-07-22 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_alter_product_active_alter_product_datetime_create'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='phone number')),
                ('State', models.CharField(max_length=15, verbose_name='state')),
                ('city', models.CharField(max_length=15, verbose_name='city')),
                ('address', models.TextField(verbose_name='address')),
                ('postal_code', models.CharField(max_length=15, verbose_name='postal code')),
                ('orders_note', models.CharField(blank=True, max_length=700, verbose_name='postal code')),
                ('datetime_create', models.DateTimeField(auto_now=True, verbose_name='Date time created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='Date time modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product')),
            ],
        ),
    ]
