# Generated by Django 4.0.2 on 2023-07-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Email',
            field=models.EmailField(blank=True, max_length=700, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orders_note',
            field=models.CharField(blank=True, max_length=700, verbose_name='oder note'),
        ),
    ]
