# Generated by Django 4.0.2 on 2023-07-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_email_alter_order_orders_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='oderitem',
            name='price_reduction',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='oderitem',
            name='reduction',
            field=models.BooleanField(default=False),
        ),
    ]
