# Generated by Django 4.0.2 on 2023-07-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_oderitem_price_reduction_oderitem_reduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='oderitem',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
