# Generated by Django 4.0.2 on 2023-07-18 13:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_comment_managers_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 13, 22, 48, 747921, tzinfo=utc)),
        ),
    ]
