# Generated by Django 4.0.2 on 2023-07-18 16:34

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_datetime_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_reduction',
            field=models.PositiveIntegerField(default=0, verbose_name='Price reduction'),
        ),
        migrations.AddField(
            model_name='product',
            name='reduction',
            field=models.BooleanField(default=False, verbose_name='reduction'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 16, 34, 40, 443556, tzinfo=utc), verbose_name='Date time created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
    ]
