# Generated by Django 4.0.2 on 2023-07-18 16:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_price_reduction_product_reduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 16, 45, 33, 853261, tzinfo=utc), verbose_name='Date time created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Short description'),
        ),
    ]
