# Generated by Django 4.0.2 on 2023-07-26 07:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_datetime_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 7, 7, 3, 814840, tzinfo=utc), verbose_name='Date time created'),
        ),
    ]
